.TH asm58 8 2010-03-30 "asm58" "Asus ASM58 Mozart 2 kernel module"
.SH NAME
asm58 \-   Kernel module for the Asus ASM58 Mozart 2 driver
.SH DESCRIPTION
.I asm58
.TP
DKMS kernel module for Asus ASM58 Mozart 2 chip to monitor temperature and fan speed
.TP
For more information please have a look at http://www.lm-sensors.org/.
.SH AUTHORS
This page written by Not Available <none@none.net>
